### ISSUE TITLE
Fail on compilation warnings

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/judge-java8#5]
The judge should fail compilation and skip tests if any warnings occur during compilation. Perhaps with a config option to turn this off.

_[Original issue](https://github.ugent.be/dodona/judge-java/issues/5) by @ninewise on Mon May 22 2017 at 17:04._
_Closed by @thepieterdc on Fri Apr 12 2019 at 14:10._

**Comment by thepieterdc** [comment]
PR #16 .

_[Original comment](https://github.ugent.be/dodona/judge-java/issues/5#issuecomment-88118) by @thepieterdc on Thu Apr 11 2019 at 17:25._
